services:
  tiket:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiket
    container_name: tiket
    restart: unless-stopped
    volumes:
      - .:/var/www/tiket
    ports:
      - 8083:80
    #  - 8443:443

  db:
    #image: mysql
    image: mariadb
    container_name: tiket-db
    restart: always
    environment:
      MYSQL_DATABASE: 'tiket'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'tiket'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'tiket'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
  
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: tiket-pma
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db

# Names our volume
volumes:
  my-db:

networks:
  default:
    external: true
    name: tiket
